version: '3.7'

#Define services
services:
  #App backend service
  card-server:
    #Configuration for building the docker image for the backend service
    image: spring-card-verifier
    build:
      context: ./ #Use an image built from the specified dockerfile in the card-verifier directory
      dockerfile: Dockerfile
    ports:
      - "8007:8080" #Forward the exposed port 8080 on the container port 8080 on the host machine
    restart: always
    depends_on:
      - "db" # This service depends on mysql. Start that first.
    environment: #Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/card_verifier?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    networks: #Netorks to join(Services on the same network can communicate with each other using their name)
    - backend
    # Database Service (Mysql)
  db:
    image: mysql:latest
    ports:
      - "6033:3306"
    restart: always
    environment:
      MYSQL_DATABASE: card_verifier
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  # Volumes
volumes:
  db-data:

  # Networks to be created to facilitate communication between containers
networks:
  backend:



